### ISSUE TITLE
Logging out then logging back in redirects to /accounts/profile/ (404)

### ISSUE THREAD

**Issue by adamstauffer** [dunbarcyber/cyclops#12]
When I logout I get properly redirected to the login page. However, when I login again I get redirected to /accounts/profile/, which is a 404. I think it should route to /app

This is on version 1.3 of cyphon

**Comment by lhadjchikh** [comment]
Sorry, that's controlled by the [LOGIN_REDIRECT_URL](https://docs.djangoproject.com/en/1.11/ref/settings/#login-redirect-url) Django setting, which I originally forgot to include in Cyphondock. Just add `LOGIN_REDIRECT_URL = '/app/'` to your `config/cyphon/settings/base.py` file, as seen [here](https://github.com/dunbarcyber/cyphondock/blob/master/config-COPYME/cyphon/settings/base.py#L33).

**Comment by adamstauffer** [comment]
works thx
